name: webauthn_secure_storage_web
description: Web implementation of the webauthn_secure_storage federated plugin.
version: 0.2.0
homepage: https://github.com/JohnGalt1717/webauthn_secure_storage

resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webauthn_secure_storage_platform_interface: ^0.2.0
  web: ">=0.5.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=5.0.0 <7.0.0'

flutter:
  plugin:
    implements: webauthn_secure_storage
    platforms:
      web:
        pluginClass: BiometricStorageWeb
        fileName: webauthn_secure_storage_web.dart
