name: webauthn_secure_storage
description: App-facing package for the webauthn_secure_storage federated plugin.
version: 0.2.1
homepage: https://github.com/JohnGalt1717/webauthn_secure_storage

resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  webauthn_secure_storage_android: ^0.2.0
  webauthn_secure_storage_darwin: ^0.2.0
  webauthn_secure_storage_linux: ^0.2.0
  webauthn_secure_storage_platform_interface: ^0.2.0
  webauthn_secure_storage_web: ^0.2.0
  webauthn_secure_storage_windows: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=5.0.0 <7.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: webauthn_secure_storage_android
      ios:
        default_package: webauthn_secure_storage_darwin
      macos:
        default_package: webauthn_secure_storage_darwin
      linux:
        default_package: webauthn_secure_storage_linux
      windows:
        default_package: webauthn_secure_storage_windows
      web:
        default_package: webauthn_secure_storage_web
